### ISSUE TITLE
Add the ability to add incidents during rides with button or volume keys.

### ISSUE THREAD

**Issue by momu** [simra-project/simra-android#16]
As it is not always easy to remember after a ride where an incident occurred, it would be helpful to use the volume keys to add an incident at the current location. The annotation can be done after the ride. A software button for adding incidents at the current location would also nice.

**Comment by selphiron** [comment]
Software button for adding incidents during the ride at the current location is possible as of #14

**Comment by momu** [comment]
Thanks, works fine.
