### ISSUE TITLE
"Annotate incident" box: black text on dark background

### ISSUE THREAD

**Issue by lumpiluk** [simra-project/simra-android#18]
The labels in the "annotate incident" popup are hard to read:
![Screenshot_20210203_171305](https://user-images.githubusercontent.com/1507049/106775390-5d5ab600-6643-11eb-89ab-b52c5dac5af0.png)

Android 10, SimRa 72.0

**Comment by selphiron** [comment]
interesting, did this come up after an Update or was it this way from the beginning for you? Do you have a dark theme activated on your phone?

**Comment by lumpiluk** [comment]
It came up after an update some time late last year. (November or October? I don't remember, unfortunately.) I'm not using a dark theme.

**Comment by lumpiluk** [comment]
Could this issue have something to do with having set the system language to English? There appear to be some unexpected differences between `app/src/main/res/values` and `app/src/main/res/values-en`.

**Comment by lumpiluk** [comment]
I was able to confirm this suspicion: Switching the Android emulator to German fixed the colors. I'd prefer not to have to do this on my actual phone, though.

**Comment by selphiron** [comment]
Fixed in b0aeba3b69ed202c3e7a27db670030de6681a4ac and is live.
