### ISSUE TITLE
Change acceleration sensor type to linear acceleration (excluding gravity)

### ISSUE THREAD

**Issue by eliasgruenewald** [simra-project/simra-android#2]
https://github.com/simra-project/simra-android/blob/6c5b4435d9e970bfb7600cce0f9c0e605cb8abc1/app/src/main/java/de/tuberlin/mcc/simra/app/main/RecorderService.java#L119

Better use `STRING_TYPE_LINEAR_ACCELERATION`.
Refer to: https://developer.android.com/reference/android/hardware/Sensor.html#TYPE_LINEAR_ACCELERATION

**Comment by selphiron** [comment]
`TYPE_LINEAR_ACCELERATION` is now recorded alongside of `TYPE_ACCELEROMETER`
