### ISSUE TITLE
Upload of collected rides not possible

### ISSUE THREAD

**Issue by fbausch** [simra-project/simra-android#29]
After the update to Android 14, it  was at first not possible to record new tracks with simra. After the app got an update last week, collection of data is now possible again.
However, I am still unable to upload the tracks to the simra servers. Using the "hochladen" button in the "Meine Fahrten" view closes the app and the rides are not uploaded.

**Comment by degutant** [comment]
I have the same issue since I updated my Samsung device to Android 14 with One UI 6.0.

When I hit the Upload button the app turns white and closes.

**Comment by fbausch** [comment]
The recent update fixed this issue for me.
